---
version: "3.8"

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Sao_Paulo
    ports:
      - 8200:8200
    volumes:
      - config:/config
      - backups:/backups
      - source:/source
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  network:
    driver: overlay
    attachable: true

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.73,rw
      device: ":/var/nfs/public/docker/volumes/duplicati/config"
  backups:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.73,rw
      device: ":/var/nfs/public/docker/volumes/duplicati/backups"
  source:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.73,rw
      device: ":/var/nfs/public/docker/volumes/duplicati/source"
